name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Hey everyone! 🎉\n\n**New Release 🚀 Version: ${{ github.event.release.tag_name }}**\n\n**What\'s Changed:**\n* ${CHANGE_DETAILS}\n\n**Full Changelog:** [View Changes](${{ github.event.release.html_url }})"}' \
               $DISCORD_WEBHOOK
