name: Discord Notification on Release

on:
  release:
    types: [created]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Construct payload with explicit newlines
          read -r -d '' PAYLOAD << EOM || true
          {
            "username": "GitHub Release Bot",
            "content": "Release: ${{ github.event.release.name }}\n${{ github.event.release.body }}"
          }
          EOM
          
          # Sending the message to Discord
          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               $DISCORD_WEBHOOK
