name: Discord Notification on Release

on:
  release:
    types: [created]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # Environment variables for release details
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          # Prepare the message content, preserving newlines
          MESSAGE_CONTENT=$(echo -e "Release: $RELEASE_NAME\n$RELEASE_BODY")
          
          # Using jq to create the JSON payload with actual newlines
          JSON_PAYLOAD=$(jq --null-input \
                            --arg content "$MESSAGE_CONTENT" \
                            '{username: "GitHub Release Bot", content: $content}')
          
          # Sending the message to Discord
          curl -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD" \
               $DISCORD_WEBHOOK
